services:
  - type: web
    name: wikai-commons
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wikai.web_ui:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
